config/routes.rb
Rails.application.routes.draw do
  	resources :tags

	resources :todo_lists do
	   resources :todo_items do
	    member do
	     patch :complete
	     patch :increment
	     patch :decrement
	    end
	  end
	end

	resources :todo_list_tags
	# get 'todo_list_tags(.:format)', :to => 'todo_list_tags#index', :as => :todo_list_tags
	delete  'todo_list_tags(.:format)', :to => 'todo_list_tags#destroy', :as => :delete_todo_list


	root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :todo_lists
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
	belongs_to :todo_list
	def completed?
   		!completed_at.blank?
  	end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	has_many :todo_items
	has_and_belongs_to_many :tags
end

app/models/todo_list_tag.rb
class TodoListTag < ApplicationRecord
  belongs_to :todo_lists
  belongs_to :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @todo_list_tags = TodoListTag.where(tags_id: params[:id]).pluck(:todo_list_id)
    @todo_lists = TodoList.where(id: @todo_list_tags)
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.delete
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name, :todo_list_id)
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	 before_action :set_todo_list
	 before_action :set_todo_item, except: [:create]

	def create
		@last_item = @todo_list.todo_items.order(:priority).last
		if @last_item == nil
			params[:todo_item][:priority] = 1
		else
			params[:todo_item][:priority] = @last_item.priority + 1
		end
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		redirect_to @todo_list
	end

	def increment
		@todo_item = @todo_list.todo_items.find(params[:id])
		before_item = @todo_list.todo_items.where("priority < ?", @todo_item.priority).order(:priority).last
		before_item.update_attribute(:priority, @todo_item.priority)
		@todo_item.update_attribute(:priority, @todo_item.priority - 1)
		redirect_to @todo_list
	end

	def decrement
		@todo_item = @todo_list.todo_items.find(params[:id])
		after_item = @todo_list.todo_items.where("priority > ?", @todo_item.priority).order(:priority).first
		after_item.update_attribute(:priority, @todo_item.priority)
		@todo_item.update_attribute(:priority, @todo_item.priority + 1)
		redirect_to @todo_list
	end

	def destroy
		@todo_item = @todo_list.todo_items.find(params[:id])
	 	if @todo_item.destroy
	 		# change every priority below to - 1
	 		@next_items = @todo_list.todo_items.where("priority > ?", @todo_item.priority)
	 		@next_items.each do |item|
	 			item.priority = item.priority - 1
	 		end
	  		flash[:success] = "Todo List item was deleted."
	 	else
	  		flash[:error] = "Todo List item could not be deleted."
	 	end
	 	redirect_to @todo_list 
	end

	def completed?
   		!completed_at.blank?
  	end

	def complete
		if @todo_item.completed?
	 		@todo_item.update_attribute(:completed_at, blank?)
	 		notice = "Todo item incomplete"
	 	else
	 		@todo_item.update_attribute(:completed_at, Time.now)
	 		notice = "Todo item completed"
	 	end
	 	redirect_to @todo_list, notice: notice
	end

	private
		def set_todo_list
		 @todo_list = TodoList.find(params[:todo_list_id])
		end
		def set_todo_item
		 @todo_item = @todo_list.todo_items.find(params[:id])
		end
		def todo_item_params
		 params[:todo_item].permit(:content, :priority)
		end
	end

app/controllers/todo_list_tags_controller.rb
class TodoListTagsController < ApplicationController
  def index
    @todo_list_tags = TodoListTag.all
  end

  def new
    @todo_list_tag = TodoListTag.new
  end

  def create
  	inserts = []
  	inserts.push "(#{params[:todo_list_id]}, #{params[:tag]})"
  	sql = "INSERT INTO todo_list_tags (todo_list_id, tags_id) VALUES #{inserts.join(", ")}"
  	ActiveRecord::Base.connection.execute(sql) 
    redirect_to :controller => 'todo_lists', action: "show", id: params[:todo_list_id]
  end

  def destroy
  	@todo_list_tag = TodoListTag.where(tags_id: params[:tag_id], todo_list_id: params[:todo_list_id])
  	if @todo_list_tag.delete_all
  		flash[:success] = "Todo List item was deleted."
  	else
  		flash[:error] = "Todo List item could not be deleted."
  	end 
    redirect_to :controller => 'todo_lists', :action => "show"
  end

  # private
  # def todo_list_tag_params
  #   byebug
  # 	params.permit(:todo_list_id, :tag)
  # end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @tag_option = Tag.pluck(:name, :id)
    @todo_list_id = params[:id]

    @todo_list_tags = TodoListTag.where(todo_list_id: params[:id]).pluck(:tags_id)
    @tags = Tag.where(id: @todo_list_tags)
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_item = @todo_list.todo_items.all
    @todo_item.delete(@todo_item)
    if @todo_list.delete
      flash[:success] = "Todo List was deleted."
    else
      flash[:error] = "Todo List could not be deleted."
    end
    redirect_to @todo_list 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
<body>
<div class="container">
    <%= yield %>
   </div>
    
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="todo_list_title">Tags</h1>


<div class = "clearfix">
  <% @tags.each do |tag| %>
    <div id = "boxed">
      <div class = "text"><%= link_to tag.name, tag %> </div>
      <%= link_to tag, method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-times"></i>
      <% end %>
    </div>
  <% end %>
</div>

<div class="links">
 <%= link_to 'New Tag', new_tag_path %> |
 <%= link_to 'Home', todo_lists_path %>
</div>

app/views/tags/new.html.erb
<h1 class="todo_list_title">New Tag</h1>

<div class="forms">
<%= render 'form', tag: @tag %>
</div>

<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/tags/show.html.erb
<div class = "edit_icon">
	<%= link_to edit_tag_path(@tag) do %> 
		<i class="fa fa-pencil-square-o fa-2x"></i>
	<% end %>
</div>

<p id="notice"><%= notice %></p>
<h2 class = "todo_list_title"><%= @tag.name %></h2>

<% @todo_lists.each do |todo_list| %>
    <div class = "todo_list_link"><%= link_to todo_list.title, todo_list %></div>
    <div class = "todo_list_sub_title"><%= todo_list.description %></div>
<% end %>

<div class="links">
	<%= link_to 'Tags', tags_path %>
</div>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
 <% if todo_item.completed? %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
   <% end %>
  </div>
  <div class="todo_item">
   <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  </div>

  <div class="pull-left">
    <span class="fa fa-stack">
        <% if @todo_list.todo_items.where("priority < ?", todo_item.priority).last != nil %>
          <%= link_to increment_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
            <i class="fa fa-caret-up"></i>
          <% end %>
        <%end%>
        <% if @todo_list.todo_items.where("priority > ?", todo_item.priority).first != nil %>
          <%= link_to decrement_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
          <i class="fa fa-caret-down"></i>
          <%end%>
        <%end%>
    </span>
  </div>

  <div class="trash">
    <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>

 <% else %>
  <div class="complete">
    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
      <i class="fa fa-circle-thin"></i>
    <% end %>
  </div>
  <div class="todo_item">
    <p><%= todo_item.content %></p>
  </div>

<div class="pull-left">
    <span class="fa fa-stack">
        <% if @todo_list.todo_items.where("priority < ?", todo_item.priority).last != nil %>
          <%= link_to increment_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
            <i class="fa fa-caret-up"></i>
          <% end %>
        <%end%>
        <% if @todo_list.todo_items.where("priority > ?", todo_item.priority).first != nil %>
          <%= link_to decrement_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
          <i class="fa fa-caret-down"></i>
          <%end%>
        <%end%>
    </span>
  </div>

  <div class = "trash">
    <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>
 <% end %>
</div>

app/views/todo_list_tags/_form.html.erb
<%= form_with(model: todo_list_tag, local: true) do |form| %>
  <% if todo_list_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list_tag.errors.count, "error") %> prohibited this todo_list_tag from being saved:</h2>

      <ul>
        <% todo_list_tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :todo_list_id %>
    <%= form.text_field :todo_list_id %>
  </div>

  <div class="field">
    <%= form.label :tags_id %>
    <%= form.text_field :tags_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_list_tags/edit.html.erb
<h1 class="todo_list_title">Editing Todo Item</h1>
<div class="forms">
<%= render 'form', todo_item: @todo_item %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_list_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="todo_list_title">Todo List Tag</h1>

<table>
  <thead>
    <tr>
      <th>Todo list ID</th>
      <th>Tag ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list_tags.each do |todo_list_tag| %>
      <tr>
        <td><%= todo_list_tag.todo_list_id %></td>
        <td><%= todo_list_tag.tags_id %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', delete_todo_list_path(todo_list_id: todo_list_tag.todo_list_id, tags_id: todo_list_tag.tags_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="links">
 <%= link_to 'New Todo List Tag', new_todo_list_tag_path %> |
 <%= link_to 'Home', todo_lists_path %>
</div>

app/views/todo_list_tags/new.html.erb
<h1 class="todo_list_title">New Todo List Tag</h1>

<div class="forms">
<%= render 'form', todo_list_tag: @todo_list_tag %>
</div>

<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_list_path(@todo_list) %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %>
<div class="links">
  <%= link_to "New Todo List", new_todo_list_path %> |
  <%= link_to "Tags", tags_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<div class = "trash_icon">
  <%= link_to todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } do %> 
    <i class="fa fa-trash fa-2x"></i>
    <% end %>
</div>

<div class = "edit_icon">
  <%= link_to edit_todo_list_path(@todo_list) do %> 
    <i class="fa fa-pencil-square-o fa-2x"></i>
    <% end %>
</div>

<p id="notice"><%= notice %></p>
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<%= form_tag(todo_list_tags_path, :method => "create") do %>
  <div id = "select"><%= select_tag :tag, options_for_select(@tag_option) %></div>
	<%= hidden_field_tag :todo_list_id, @todo_list_id %>
	<div id = "tag_submit"><%= submit_tag("Add tag") %></div>
<% end %>

<div class = "clearfix">
<% @tags.each do |tag| %>
  <div id = "boxed">
    <div class = "text"><%= link_to tag.name, tag %></div>
    <%= link_to todo_list_tag_path(:tag_id => tag.id, :todo_list_id => @todo_list.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-times"></i>
    <% end %>
  </div>
<% end %>
</div>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items.order(:priority) %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<div class="links">
 <%= link_to 'Home', todo_lists_path %>
</div>